### PR TITLE
CSS Custom Properties: Common

### PR DESCRIPTION
**Pull request by 0aveRyan**
As I was exploring work on `site-health.css` and following #4, it really seems like there needs to be _some_ common properties.

I know there's all sorts of [exciting grand plans](https://codepen.io/ryelle/full/WNGVEjw) and [discussion around what variables should exist](https://make.wordpress.org/core/2021/01/29/introducing-css-custom-properties/), nomenclature, concerns about public API maintenance burden, etc.

But, to even tackle this first round of Custom Properties, it seems we need to have some basic properties that aren't Theme-specific that persist regardless of dark mode, active admin color scheme, etc. Otherwise we're going to be adding an exhaustive number of Custom Properties for things like "success", "warning", "info" and "color."

So as an iterative step I'd propose we have a very limited set of "common" variables outside the `--prefix--location--property-state` to prevent the need to set dozen(s) of properties all to override the same hex.

Thoughts?

### CODE REVIEW

**Comment by circlecube** [comment]
I would strongly agree here. From the work I was doing on #6  it was apparent there was going to be lots of duplication of hex values since we don't have a common set of colors defined anywhere. I think this would be a great and simple addition here. 

Perhaps even adding a spectrum of gray colors? There are a good number used in #6 that aren't defined or defined in places that are too specific to reuse the hex for certain elements.

Defining the common color palette would benefit each step of this process. Using the approved color palette (https://codepen.io/ryelle/full/WNGVEjw) could be the wise and make it the only place hex values are defined. Then in all the other definitions the proper color is assigned. This will help immensely once we get to consolidating colors.

**Comment by 0aveRyan** [comment]
Gentle bump on this @ryelle as we never circled back to this in the meeting two weeks ago.

There are definitely other ways to do this but some kind of color palette abstracted from specific uses would help reduce the quantity that require override if someone was customizing.

We can carry on as we have been duping color codes, but something to this effect would be helpful!

**Comment by ryelle** [comment]
There are a few existing "theme" colors (following how Gutenberg sets up variables), for the primary color & notification:

https://github.com/ryelle/wordpress-develop/blob/db2eff97c0cdce29d4b568fe2d2b186be5d4da97/src/wp-includes/css/custom-properties.css#L2-L6

I think you're right that we should have a few shared colors for error/alert/info…, but I think they should follow the `--theme--` naming scheme.

```
--wp-admin--theme--primary: #2271b1;
...
--wp-admin--theme--success: #00a32a;
--wp-admin--theme--info: #72aee6;
--wp-admin--theme--warning: #dba617;
--wp-admin--theme--error: #d63638;
```

I'm not sure about using these everywhere that hex color is used, though, there might be places where the hex value is used but it's not meant to be "warning"/etc. Like the star rating, I don't think that's intentionally a "warning" yellow, it's just the yellow that works there.

------

> Defining the common color palette would benefit each step of this process. Using the approved color palette could be the wise and make it the only place hex values are defined.

We decided not to set up base colors as custom properties, but we could circle back to the idea of setting up a sass process to generate the `custom-properties.css` file. In another project I'm working on, I have [a map of colors](https://github.com/WordPress/pattern-directory/blob/1d78c283598cd874c0d23143b07db57d3ad0b229/public_html/wp-content/themes/pattern-directory/css/settings/_colors.scss#L32) which can be used via a Sass function like `color: color(red-50);`. Would that be worth doing here?

**Comment by 0aveRyan** [comment]
@ryelle Sounds good. I'll update this PR for `--wp-admin--theme--STATUS` naming convention and remove the "Yellow Star" swap.

I don't know if the full map is necessary _yet_ to get through a first phase of this project. But after a few files I definitely was feeling repetitive for the status colors.

Always going to be a few snowflakes, but I think the base color abstraction for statuses makes it a more-helpful API. Changing those four properties is much easier than learning and locating one-few dozen contextual properties, while also allowing those contextual properties to each receive their own unique treatment if a developer wanted to.

**Comment by ryelle** [comment]
Merged in https://github.com/ryelle/wordpress-develop/commit/e531b2f5dbf23aad2c5732843382b918c90984b3 - thanks!

**Pull request closed without merging**
